export const MASSAGES_ONLINE = [
	{
		id: 1,
		name: "user1",
		img: "/assets/images/online_image1.svg",
		img_alt: "user1",
		online: true,
	},
	{
		id: 2,
		name: "user2",
		img: "/assets/images/online_image2.svg",
		img_alt: "user1",
		online: true,
	},
	{
		id: 3,
		name: "user3",
		img: "/assets/images/online_image4.svg",
		img_alt: "user3",
		online: true,
	},
	{
		id: 4,
		name: "user4",
		img: "/assets/images/online_image4.svg",
		img_alt: "user4",
		online: true,
	},
	{
		id: 5,
		name: "user5",
		img: "/assets/images/online_image4.svg",
		img_alt: "user5",
		online: true,
	},
	{
		id: 6,
		name: "user1",
		img: "/assets/images/online_image1.svg",
		img_alt: "user1",
		online: true,
	},
	{
		id: 7,
		name: "user2",
		img: "/assets/images/online_image2.svg",
		img_alt: "user1",
		online: true,
	},
	{
		id: 8,
		name: "user3",
		img: "/assets/images/online_image4.svg",
		img_alt: "user3",
		online: true,
	},
	{
		id: 9,
		name: "user4",
		img: "/assets/images/online_image4.svg",
		img_alt: "user4",
		online: true,
	},
	{
		id: 10,
		name: "user5",
		img: "/assets/images/online_image4.svg",
		img_alt: "user5",
		online: true,
	},
	{
		id: 11,
		name: "user6",
		img: "/assets/images/online_image6.svg",
		img_alt: "user6",
		online: true,
	},
	{
		id: 12,
		name: "Anne Snow",
		img: "/assets/images/message_img1.svg",
		img_alt: "Anne Snow",
		messages: ["did you get it?", "Hello!"],
		online: true,
		read: false,
	},
	{
		id: 13,
		name: "Sara Williams",
		img: "/assets/images/message_img2.svg",
		img_alt: "Sara Williams",
		messages: ["Hello!", "Hi", "okay", "Thank you for the support"],
		online: false,
		read: false,
	},
	{
		id: 14,
		name: "John Smith",
		img: "/assets/images/message_img3.svg",
		img_alt: "John Smith",
		messages: ["Hello!", "No worries"],
		online: false,
		read: true,
	},
	{
		id: 15,
		name: "John Snow",
		img: "/assets/images/message_img4.svg",
		img_alt: "John Snow",
		messages: ["Hello!", "Hello!"],
		online: true,
		read: true,
	},
	{
		id: 16,
		name: "Sara Williams",
		img: "/assets/images/message_img5.svg",
		img_alt: "Sara Williams",
		messages: ["Hello!", "Hi", "okay", "Thank you for the support"],
		online: false,
		read: true,
	},
	{
		id: 17,
		name: "John Smith",
		img: "/assets/images/message_img6.svg",
		img_alt: "John Smith",
		messages: ["Hello!", "No worries"],
		online: true,
		read: true,
	},
	{
		id: 18,
		name: "John Snow",
		img: "/assets/images/message_img7.svg",
		img_alt: "John Snow",
		messages: ["Hello!", "No worries"],
		online: false,
		read: true,
	},
];
